// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAEI-0Pot_4_qufB5VbSd4lmSKZfmL4Fk',
    appId: '1:17664552951:web:4abe03612b6ad97bb508f2',
    messagingSenderId: '17664552951',
    projectId: 'geo-fusion-app-1e018',
    authDomain: 'geo-fusion-app-1e018.firebaseapp.com',
    storageBucket: 'geo-fusion-app-1e018.firebasestorage.app',
    measurementId: 'G-PEXTD896PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkwHkbCtTC3UYtliA-5BEbSOep0SLzwbg',
    appId: '1:17664552951:android:970f61078fc1707db508f2',
    messagingSenderId: '17664552951',
    projectId: 'geo-fusion-app-1e018',
    storageBucket: 'geo-fusion-app-1e018.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgWQNFcE-njU8Z9G9JisEiMCRIcSApgQk',
    appId: '1:17664552951:ios:091f564fb080f37ab508f2',
    messagingSenderId: '17664552951',
    projectId: 'geo-fusion-app-1e018',
    storageBucket: 'geo-fusion-app-1e018.firebasestorage.app',
    iosBundleId: 'com.example.gpsMapCameraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgWQNFcE-njU8Z9G9JisEiMCRIcSApgQk',
    appId: '1:17664552951:ios:091f564fb080f37ab508f2',
    messagingSenderId: '17664552951',
    projectId: 'geo-fusion-app-1e018',
    storageBucket: 'geo-fusion-app-1e018.firebasestorage.app',
    iosBundleId: 'com.example.gpsMapCameraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAEI-0Pot_4_qufB5VbSd4lmSKZfmL4Fk',
    appId: '1:17664552951:web:ea17b341caa377f0b508f2',
    messagingSenderId: '17664552951',
    projectId: 'geo-fusion-app-1e018',
    authDomain: 'geo-fusion-app-1e018.firebaseapp.com',
    storageBucket: 'geo-fusion-app-1e018.firebasestorage.app',
    measurementId: 'G-6EY2YQ5NJG',
  );
}
